### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Giseli Carvalho",
  "email": "gabrieldnsilva@example.com",
  "address": "Rua Noé de Freitas, 7",
  "dateOfBirth": "1994-06-12",
  "registeredDate": "2025-08-03"
}
###